# ~/.config/starship.toml

add_newline = true

[username]
style_user = "yellow"
style_root = "black bold"
format = " [@$user]($style) on"
disabled = false
show_always = true

[hostname]
ssh_only = false
format =  " [$hostname](bold blue) "
trim_at = "."
disabled = false

[shell]
powershell_indicator = "[pwsh](blue)"
bash_indicator = "[bash](yellow)"
unknown_indicator = "mystery shell"
disabled = false

[shlvl]
disabled = false
format = "[$symbol$shlvl]($style) "
threshold = 2

[character]
success_symbol = "[>](green) "
error_symbol = "[<](red) "


[directory]
read_only = "  "
truncation_symbol = " ../"

[time]
disabled = false
format = '[\[ $time \]]($style) '
time_format = "%T"
utc_time_offset = "-3"

[cmd_duration]
min_time = 1_000
show_milliseconds = true

[aws]
symbol = " "

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[conda]
ignore_base = false
symbol = " "
format = "[$symbol$environment](dimmed green) "

[docker_context]
symbol = " "

[dotnet]
symbol = " "
format = "[$symbol$version( 什 $tfm)]($style) "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "
style = "bold purple"
format ="-- [$symbol$branch ]($style)"


[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "
python_binary = "python3"

[ruby]
symbol = " "

[rust]
symbol = " "
